### ISSUE TITLE
nphysics example crashed

### ISSUE THREAD

**Issue by happydpc** [MeirBon/rfw-rs#9]
These are the error log. Seems that  write_texture call is not correct.
```rust
thread 'main' panicked at 'range end index 20480 out of range for slice of length 16384', renderers\deferred\src\lib.rs:524:22
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d\/library\std\src\panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d\/library\core\src\panicking.rs:85
   2: core::slice::slice_end_index_len_fail
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d\/library\core\src\slice\mod.rs:3149
   3: core::slice::{{impl}}::index<u8>
             at C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\slice\mod.rs:3338
   4: core::slice::{{impl}}::index<u8,core::ops::range::Range<usize>>
             at C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\slice\mod.rs:3123
   5: alloc::vec::{{impl}}::index<u8,core::ops::range::Range<usize>>
             at C:\Users\Administrator\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc\src\vec.rs:2012     
   6: rfw_deferred::{{impl}}::set_textures
             at .\renderers\deferred\src\lib.rs:524
```

**Comment by MeirBon** [comment]
Mip maps were not generated for the default texture and the renderer created textures with incorrect mip levels, it's fixed now :)

**Comment by happydpc** [comment]
Yeah, it's ok now. Wonderful job.

**Comment by MeirBon** [comment]
Thanks for reporting!
